### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by zengonly** [Wonail/wocenter_doc#1]
![image](https://user-images.githubusercontent.com/21103564/31080150-7ae2d248-a7ba-11e7-9a28-fb36977a042c.png)

**Comment by e-kevin** [comment]
`console`应用的`id`应由原来的'app-condole`更改为'console'，这个问题已经在未发布的版本里得到修复。谢谢反馈。这是`wocenter`核心的问题，建议反馈在[wocenter项目](https://github.com/Wonail/wocenter)

**Comment by zengonly** [comment]
好的
